### ISSUE TITLE
运行出现

### ISSUE THREAD

**Issue by wangyanhui406874** [F6JO/Suture_Box#1]
![image](https://user-images.githubusercontent.com/93036554/163699287-002fe3ef-1784-46ed-aadb-507b0258d666.png)

**Comment by F6JO** [comment]
python3 -m pip install tqdm

**Comment by F6JO** [comment]
> ![image](https://user-images.githubusercontent.com/93036554/163699287-002fe3ef-1784-46ed-aadb-507b0258d666.png)

python3 -m pip install tqdm
